source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
# Uncomment the next line to define a global platform for your project
 #platform :ios, '8.0'
 platform :ios, '12'

target 'ProCoin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  
  # 刷新tableview
  pod 'MJRefresh'
  
  # GIF展示控件
  pod 'FLAnimatedImage'
  
  # 网络图片显示cd 
  pod 'SDWebImage'
  
  # segment选择器
  pod 'YNPageViewController'

  # 多媒体选择器
 
 pod 'TZImagePickerController' #iOS8 and later


  # 微信SDK
  pod 'WechatOpenSDK'
  
  # 按钮菜单
  pod 'LvPopupMenu'

  # TCP
  pod 'SocketRocket'

  # 图标变换按钮
  pod 'FRDLivelyButton'
  
  pod 'QMUIKit'
  
  pod 'Masonry'
  pod 'YYText'
  pod 'YYModel'
  pod 'SDCycleScrollView'
  pod 'JXCategoryView'
  pod 'JXPagingView/Pager'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['LD_NO_PIE'] = 'NO'
      end
    end
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
